### ISSUE TITLE
Allow orgwide import

### ISSUE THREAD

**Issue by nia-potato** [backtostage/backstage-plugins#159]
Hi @angeliski  

Thanks for the great plugin, is there any way to allow these catalog import plugin, on the gcp org level? and we allow service account permissions to allow all these imports to do discovery on the org level? for all the types you specified? 
  - cloud
  - project
  - resources
  - gcp
  - cloudsql

**Comment by angeliski** [comment]
Hi @nia-potato 

Could you elaborate more what are you expecting? I understand the problem (because now we need to find each project and config for that), but I want to understand more what are you expectation here. 

What you what to see the import do?

I have plans to work toward a more seamless integration, but now I am looking for early feedback too, so I am happy to listenen your feedback

**Comment by nia-potato** [comment]
@angeliski yea sorry for the delay, so this is the current config: 
```
      - project: my-gcp-project-id
        ownerLabel: team # string
        componentLabel: app # string
        cloudsql:
          resourceType: SQL  # string
        redis:
          resourceType: Redis  # string
          location: us-central1 # string
        schedule: # same options as in TaskScheduleDefinition
          # supports cron, ISO duration, "human duration" as used in code
          frequency: { minutes: 30 }
          # supports ISO duration, "human duration" as used in code
          timeout: { minutes: 3 }
```

i was wondering if it could be like this, where the backstage google service account would then be granted org wide, so we do not need declare it to each project. however the problem how would we extract the `ownerLabel`  and i think we should also have option to import this as a backstage `kind:Resource` `type:redis` , `type:spanner`, `type:cloudsql`. idk if this is helpful feedback. 

```
      - orgId: #######  gcp OrgId 
        cloudsql:
          resourceType: SQL  
        redis:
          resourceType: Redis  # string
        spanner:
    
        schedule: # same options as in TaskScheduleDefinition
          # supports cron, ISO duration, "human duration" as used in code
          frequency: { minutes: 30 }
          # supports ISO duration, "human duration" as used in code
          timeout: { minutes: 3 }
          
```
